{"name": "Тест принятия заказа курьером", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "@pytest.fixture(scope='session')\n    def get_id_courier():\n>       return methods_api.get_courier_id()\n\ntests/test_accept_order.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def get_courier_id():\n        data_example = data_generator.register_courier_full_data()\n        response_create_courier = requests.post(f'{Urls.main_page}{Handle.create_courier}', data_example)\n>       assert response_create_courier.status_code == 201\nE       AssertionError\n\nmethods_api.py:17: AssertionError"}, "description": "Проверка назначения на полученный id заказа курьера  ", "start": 1729653410246, "stop": 1729653410246, "uuid": "9cd32439-4f30-4e7d-a107-e864b5fc6310", "historyId": "54eeff126aa71d66b9fc66a126d90460", "testCaseId": "54eeff126aa71d66b9fc66a126d90460", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_positive", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "192.168.1.40"}, {"name": "thread", "value": "30228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}