{"name": "Негативный ест приятия заказа курьером", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "@pytest.fixture(scope='session')\n    def get_id_courier():\n>       return methods_api.get_courier_id()\n\ntests/test_accept_order.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def get_courier_id():\n        data_example = data_generator.register_courier_full_data()\n        response_create_courier = requests.post(f'{Urls.main_page}{Handle.create_courier}', data_example)\n>       assert response_create_courier.status_code == 201\nE       AssertionError\n\nmethods_api.py:17: AssertionError"}, "description": "id заказа неверный и пустой ", "parameters": [{"name": "id_order", "value": "373"}], "start": 1729653440621, "stop": 1729653440621, "uuid": "bae65828-d0be-47df-8035-f72df1752bb7", "historyId": "98670e03ed5e4f1ec3f9447337d0a382", "testCaseId": "be6043b90147f4b673946c3f0b25fe06", "fullName": "tests.test_accept_order.TestAcceptOrder#test_accept_order_negative_data_id_order", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_accept_order"}, {"name": "subSuite", "value": "TestAcceptOrder"}, {"name": "host", "value": "192.168.1.40"}, {"name": "thread", "value": "30228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_accept_order"}]}